apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: i3g0qxgif-nodejs 
  janus-idp.io/tekton: i3g0qxgif-nodejs
  backstage.io/kubernetes-id: i3g0qxgif-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i3g0qxgif-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml