apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i3g0qxgif-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i3g0qxgif-nodejs 
  name: i3g0qxgif-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: i3g0qxgif-nodejs 
